version: '3.7'

services:
    db:
        image: mysql:8.0
        container_name: swii-database
        volumes: 
            - ./db_data:/var/lib/mysql
        ports: 
            - 8886:3306
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: swiiproject
            MYSQL_DATABASE: swii
            MYSQL_USER: users
            MYSQL_PASSWORD: users
            url: jdbc:mysql://localhost:8886/swii?serverTimezone=UTC
            driver-class-name: com.mysql.jdbc.Driver